### ISSUE TITLE
insertbefore, insertafter that do not drop entries 

### ISSUE THREAD

**Issue by JeffreySarnoff** [Jutho/TupleTools.jl#1]
This tool grouping is a good idea (imo).
I would use insertbefore and insertafter 
`insert<before|after>(tuple1, index (1:length(tuple1)), tuple2)`
if they did not overwrite/eliminate an extant value (the insertion occurs (a) in front of tuple1 (b) in back of tuple1 (c) between two positions of tuple1).

**Comment by Jutho** [comment]
I am not sure I understand all the requests. You want both `insertbefore` and `insertafter`? What do you mean with 

> c) between two positions of tuple1).

**Comment by JeffreySarnoff** [comment]
```
tuple1 = (1, 2); tuple2 = (8, 9);

insert_this_before_that:
   insert_tuple2_into_tuple1_before_index#2 == (1, 8, 9, 2)

insert_this_after_that:
   insert_tuple2_into_tuple1_after_index#2 == (1, 2, 8, 9)
```
if tuple2 is inserted into tuple1, tuple2 either preceeds tuple1 or follows tuple1 or (c) is positioned between two adjacent elements of tuple1.

insert_this_before_that:
   insert_tuplew_into_tuple1_before_index#2 == (1, 8, 9, 2)

insert_this_after_that:
   insert_tuplew_into_tuple1_after_index#2 == (1, 2, 8, 9)
```

**Comment by Jutho** [comment]
Is a single function `insertafter` sufficient, where, in order to insert `tuple2` in front of `tuple 1`, you use index `0`  (ore more simply just `(tuple2...,tuple1...)` )

**Comment by JeffreySarnoff** [comment]
yes

**Comment by Jutho** [comment]
This should be fixed now and I tagged a new version right away. Let me know if you encounter any problems.
