### ISSUE TITLE
add flatten() like deepvcat()?

### ISSUE THREAD

**Issue by JeffreySarnoff** [Jutho/TupleTools.jl#5]
```julia

"""
    flatten(args...) -> ::Tuple    or   deepvcat(args...) -> ::Tuple
Like a recursive `vcat` for tuples, concatenates a combination of tuple arguments
and non-tuple arguments into a single tuple. Tuples in tuples are expanded.
"""
```

sum(flatten(args...)   _or_  sum(deepvcat(args...))

**Comment by Jutho** [comment]
Seems like a good suggestion. While `flatten` seems like a nice name, the `flatten` in `Base.Iterators` also does not act recursively. Is there something like the requested behavior/functionality in Base?

**Comment by Roger-luo** [comment]
Which name is preferred? `flatten`? I could add this to `TupleTools` before you tag a new version, we don't need worry what's in the `Base.Iterators` anyway, since it's not exported, e.g

```julia
flatten(a::Tuple, b::Tuple...) = (a..., flatten(b...)...)
flatten(a::Tuple) = a
```

**Comment by Jutho** [comment]
There is now a `TupleTools.flatten` function in the latest master; I will tag v 1.1 soon

**Comment by JeffreySarnoff** [comment]
maybe
```
export flatten

import Base.Iterators.flatten
flatten(x::Tuple) = TupleTools.flatten(x)

```

**Comment by Jutho** [comment]
It's the general policy of TupleTools not to export any method, nor to overload the Base methods. Indeed, this would be type piracy. Tuples are not types defined in or intrinsic to TupleTools. Hence, any methods defined on tuples need to be new methods that are "property" of TupleTools.

**Comment by JeffreySarnoff** [comment]
ok makes sense

**Comment by Jutho** [comment]
I think this can be closed.
