### ISSUE TITLE
deleteat error-check logic fails

### ISSUE THREAD

**Issue by under-Peter** [Jutho/TupleTools.jl#6]
https://github.com/Jutho/TupleTools.jl/blob/a898092ea5bed41dd20e64ef8e6d7010b2e12d64/src/TupleTools.jl#L85

Hi,
there's an error in the logic of the error checking in deleteat, which throws an error if any of the indices to be deleted are within the range 1:length(tuple). Instead it should be either
`all(i -> (1 <= i <= length(t), I) || throw(BoundsError(I,t))`
or
`any(i -> !(1 <= i <= length(t), I) && throw(BoundsError(I,t))`

Since it's just a one character change I don't bother learning how PRs work, I hope that's alright.
Maybe an example could be added in the testfile too for deleting more than one index.

Additionally, the function returns only correct results if the tuple of indices to be deleted is sorted from big to small (as it says in the code). I changed 
https://github.com/Jutho/TupleTools.jl/blob/5eb5f3483b5c8f83948f750ca0a35c8d81c2e564/src/TupleTools.jl#L86
to 
`deleteat(_deleteat(t, I[1]), ishift(tail(I), I[1], -1))`
 i.e. replaced the first `_deleteat` with `deleteat`. This way it works as as one would expect although slower - there could be another version of `deleteat` which guarantees that the indices to be deleted are sorted for faster execution.

cheers

**Comment by Jutho** [comment]
Thanks for this, you are correct. I'll try to push an update soon.

**Comment by Roger-luo** [comment]
Guess this is fixed by https://github.com/Jutho/TupleTools.jl/commit/cda9e309e4b2cf03bdb5cbf9b30dfbb8c3582d7f ?

**Comment by Jutho** [comment]
Yes it should indeed be fixed.
