### ISSUE TITLE
Merging to Julia Base

### ISSUE THREAD

**Issue by aminya** [Jutho/TupleTools.jl#9]
Hi @Jutho 
These methods are very useful, and I think they should be included in Julia base. Would you consider submitting it as PR?

**Comment by Jutho** [comment]
Thanks; maybe some functionality could succeed as a PR to base, but I think not all of it is fit for this. Furthermore, this was written during the time of Julia 0.6. Tuple support in Base has certainly improved (especially by modifying removing some constraints on tuple sizes in the compiler/type inference mechanism), and some of functionality here provided can now also be elegantly handled by combining tuples with broadcasting.

As such, I think it is a non-trivial exercise to go through this package and decide which functionality would be of benefit to Julia Base. I am currently investing my development time elsewhere, but I am certainly open to specific suggestions.

**Comment by aminya** [comment]
I can look into adding some methods to Base using this package if you are OK

**Comment by Jutho** [comment]
That is certainly ok for me, but I won't be able to provide any support or feedback the next two weeks, as I will be mostly without internet access.
